"use client";

import React, { createContext, useContext, useState, useEffect } from "react";

export type SupportedLanguage =
  | "English"
  | "हिन्दी (Hindi)"
  | "मराठी (Marathi)"
  | "ಕನ್ನಡ (Kannada)"
  | "தமிழ் (Tamil)"
  | "తెలుగు (Telugu)"
  | "ગુજરાતી (Gujarati)"
  | "বাংলা (Bengali)"
  | "മലയാളം (Malayalam)"
  | "ਪੰਜਾਬੀ (Punjabi)"
  | "ଓଡ଼ିଆ (Odia)";

interface LanguageContextType {
  language: SupportedLanguage;
  setLanguage: (lang: SupportedLanguage) => void;
  t: (key: string) => string;
}

const translations: Record<string, Record<string, string>> = {
  English: {
    home: "Home",
    land: "Land",
    notice: "Notice",
    measurements: "Measurements",
    verification: "Verification",
    resources: "Resources",
    help: "Help",
    login: "Login",
    getStarted: "Get Started",
    heroTitlePre: "Understand Land Records Through ",
    heroTitleSpan: "Data and Maps",
    heroSubtitle: "An interactive platform for parcel visualization, record consistency analysis and land-data intelligence.",
    exploreMap: "Explore Demo Map",
    searchRecords: "Search Land Records",
    watchVideo: "Watch How It Works",
    interactiveMap: "Interactive Map",
    landMeasurement: "Land Measurement",
    recordVerification: "Record Verification",
    detailedReports: "Detailed Reports",
    riskAnalysis: "Risk Analysis",
    roleBasedAccess: "Role-Based Access",
    howItWorks: "How It Works",
    howItWorksSub: "A simple and transparent process to explore and verify land records",
    searchLand: "Search Land",
    exploreAnalyze: "Explore & Analyze",
    verifyRecords: "Verify Records",
    getReport: "Get Demo Report",
    transparentReady: "Transparent. Reliable. Future-Ready.",
    smarterApproach: "A Smarter Approach to Land Data",
  },
  "हिन्दी (Hindi)": {
    home: "मुख्य पृष्ठ",
    land: "भूमि खोज",
    notice: "सूचनाएं",
    measurements: "भू-मापन",
    verification: "सत्यापन",
    resources: "संसाधन",
    help: "सहायता",
    login: "लॉगिन",
    getStarted: "शुरू करें",
    heroTitlePre: "डेटा और नक्शों के माध्यम से समझें ",
    heroTitleSpan: "भूमि रिकॉर्ड",
    heroSubtitle: "प्लॉट विज़ुअलाइज़ेशन, रिकॉर्ड संगति विश्लेषण और भूमि-डेटा इंटेलिजेंस के लिए एक इंटरैक्टिव प्लेटफॉर्म।",
    exploreMap: "नक्शा देखें",
    searchRecords: "भूमि रिकॉर्ड खोजें",
    watchVideo: "प्रक्रिया वीडियो देखें",
    interactiveMap: "इंटरएक्टिव नक्शा",
    landMeasurement: "भूमि मापन",
    recordVerification: "रिकॉर्ड सत्यापन",
    detailedReports: "विस्तृत रिपोर्ट",
    riskAnalysis: "जोखिम विश्लेषण",
    roleBasedAccess: "भूमिका-आधारित पहुंच",
    howItWorks: "यह कैसे काम करता है",
    howItWorksSub: "भूमि रिकॉर्ड की जांच और सत्यापन के लिए एक सरल और पारदर्शी प्रक्रिया",
    searchLand: "भूमि खोजें",
    exploreAnalyze: "खोजें और विश्लेषण करें",
    verifyRecords: "रिकॉर्ड सत्यापित करें",
    getReport: "रिपोर्ट प्राप्त करें",
    transparentReady: "पारदर्शी। विश्वसनीय। भविष्य के लिए तैयार।",
    smarterApproach: "भूमि डेटा के लिए एक बेहतर दृष्टिकोण",
  },
  "मराठी (Marathi)": {
    home: "मुख्यपृष्ठ",
    land: "जमीन शोधा",
    notice: "सूचना",
    measurements: "जमीन मोजणी",
    verification: "पडताळणी",
    resources: "संसाधने",
    help: "मदत",
    login: "लॉगिन",
    getStarted: "सुरू करा",
    heroTitlePre: "डेटा आणि नकाशांद्वारे समजावून घ्या ",
    heroTitleSpan: "जमीन नोंदी",
    heroSubtitle: "प्लॉट व्हिज्युअलायझेशन, नोंद सुसंगतता विश्लेषण आणि जमीन-डेटा बुद्धिमत्तेसाठी एक परस्परसंवादी प्लॅटफॉर्म.",
    exploreMap: "नकाशा एक्सप्लोर करा",
    searchRecords: "जमीन नोंदी शोधा",
    watchVideo: "व्हिडिओ पहा",
    interactiveMap: "परस्परसंवादी नकाशा",
    landMeasurement: "जमीन मोजणी",
    recordVerification: "नोंद पडताळणी",
    detailedReports: "सविस्तर अहवाल",
    riskAnalysis: "धोक्याचे विश्लेषण",
    roleBasedAccess: "भूमिका आधारित प्रवेश",
    howItWorks: "हे कसे कार्य करते",
    howItWorksSub: "जमिनीच्या नोंदी तपासण्यासाठी आणि पडताळण्यासाठी एक सोपी प्रक्रिया",
    searchLand: "जमीन शोधा",
    exploreAnalyze: "एक्सप्लोर करा आणि विश्लेषण करा",
    verifyRecords: "नोंदी पडताळा",
    getReport: "अहवाल मिळवा",
    transparentReady: "पारदर्शक. विश्वासार्ह. भविष्यासाठी सज्ज.",
    smarterApproach: "जमीन डेटासाठी अधिक स्मार्ट दृष्टिकोन",
  },
  "ಕನ್ನಡ (Kannada)": {
    home: "ಮುಖ್ಯಪುಟ",
    land: "ಭೂಮಿ ಹುಡುಕಾಟ",
    notice: "ಸೂಚನೆಗಳು",
    measurements: "ಭೂ ಮಾಪನ",
    verification: "ಪರಿಶೀಲನೆ",
    resources: "ಸಂಪನ್ಮೂಲಗಳು",
    help: "ಸಹಾಯ",
    login: "ಲಾಗಿನ್",
    getStarted: "ಪ್ರಾರಂಭಿಸಿ",
    heroTitlePre: "ದತ್ತಾಂಶ ಮತ್ತು ನಕ್ಷೆಗಳ ಮೂಲಕ ಗ್ರಹಿಸಿ ",
    heroTitleSpan: "ಭೂ ದಾಖಲೆಗಳು",
    heroSubtitle: "ಭೂ ಪಾರ್ಸೆಲ್ ವೀಕ್ಷಣೆ ಮತ್ತು ದಾಖಲೆಗಳ ಪರಿಶೀಲನೆಗಾಗಿ ಸಂವಾದಾತ್ಮಕ ವೇದಿಕೆ.",
    exploreMap: "ನಕ್ಷೆ ವೀಕ್ಷಿಸಿ",
    searchRecords: "ದಾಖಲೆ ಹುಡುಕಿ",
    watchVideo: "ವೀಡಿಯೊ ವೀಕ್ಷಿಸಿ",
    interactiveMap: "ಸಂವಾದಾತ್ಮಕ ನಕ್ಷೆ",
    landMeasurement: "ಭೂ ಮಾಪನ",
    recordVerification: "ದಾಖಲೆ ಪರಿಶೀಲನೆ",
    detailedReports: "ವಿವರವಾದ ವರದಿಗಳು",
    riskAnalysis: "ಅಪಾಯ ವಿಶ್ಲೇಷಣೆ",
    roleBasedAccess: "ಪಾತ್ರ ಆಧಾರಿತ ಪ್ರವೇಶ",
    howItWorks: "ಇದು ಹೇಗೆ ಕಾರ್ಯನಿರ್ವಹಿಸುತ್ತದೆ",
    howItWorksSub: "ಭೂ ದಾಖಲೆಗಳನ್ನು ಪರಿಶೀಲಿಸಲು ಸರಳ ಮತ್ತು ಪಾರದರ್ಶಕ ಪ್ರಕ್ರಿಯೆ",
    searchLand: "ಭೂಮಿ ಹುಡುಕಿ",
    exploreAnalyze: "ವಿಶ್ಲೇಷಿಸಿ",
    verifyRecords: "ದಾಖಲೆ ಪರಿಶೀಲಿಸಿ",
    getReport: "ವರದಿ ಪಡೆಯಿರಿ",
    transparentReady: "ಪಾರದರ್ಶಕ. ವಿಶ್ವಾಸಾರ್ಹ.",
    smarterApproach: "ಸ್ಮಾರ್ಟ್ ಭೂ ದತ್ತಾಂಶ ವಿಧಾನ",
  },
  "தமிழ் (Tamil)": {
    home: "முகப்பு",
    land: "நில தேடல்",
    notice: "அறிவிப்புகள்",
    measurements: "நில அளவீடு",
    verification: "சரிபார்ப்பு",
    resources: "வளங்கள்",
    help: "உதவி",
    login: "உள்நுழைவு",
    getStarted: "தொடங்கவும்",
    heroTitlePre: "தரவு மற்றும் வரைபடங்கள் மூலம் புரிந்து கொள்ளுங்கள் ",
    heroTitleSpan: "நிலப் பதிவுகள்",
    heroSubtitle: "நில வரைபடம் மற்றும் ஆவண சரிபார்ப்புக்கான ஊடாடும் தளம்.",
    exploreMap: "வரைபடத்தை ஆராயுங்கள்",
    searchRecords: "பதிவுகளைத் தேடுங்கள்",
    watchVideo: "வீடியோவைப் பாருங்கள்",
    interactiveMap: "ஊடாடும் வரைபடம்",
    landMeasurement: "நில அளவீடு",
    recordVerification: "ஆவணச் சரிபார்ப்பு",
    detailedReports: "விரிவான அறிக்கைகள்",
    riskAnalysis: "அபாய பகுப்பாய்வு",
    roleBasedAccess: "பங்கு சார்ந்த அணுகல்",
    howItWorks: "இது எவ்வாறு செயல்படுகிறது",
    howItWorksSub: "நிலப் பதிவுகளைச் சரிபார்க்க எளிய மற்றும் வெளிப்படையான செயல்முறை",
    searchLand: "நிலத்தைத் தேடுங்கள்",
    exploreAnalyze: "ஆராயுங்கள் & பகுப்பாய்வு செய்யுங்கள்",
    verifyRecords: "பதிவுகளைச் சரிபாருங்கள்",
    getReport: "அறிக்கையைப் பெறுங்கள்",
    transparentReady: "வெளிப்படையான. நம்பிக்கையான.",
    smarterApproach: "நிலத் தரவுகளுக்கான புத்திசாலித்தனமான அணுகுமுறை",
  },
  "తెలుగు (Telugu)": {
    home: "హోమ్",
    land: "భూమి శోధన",
    notice: "నోటీసులు",
    measurements: "భూ కొలతలు",
    verification: "తనిఖీ",
    resources: "వనరులు",
    help: "సహాయం",
    login: "లాగిన్",
    getStarted: "ప్రారంభించండి",
    heroTitlePre: "డేటా మరియు మ్యాప్‌ల ద్వారా అర్థం చేసుకోండి ",
    heroTitleSpan: "భూ రికార్డులు",
    heroSubtitle: "భూమి ప్లాట్ల పరిశీలన మరియు రికార్డుల తనిఖీకి ఇంటరాక్టివ్ వేదిక.",
    exploreMap: "మ్యాప్‌ను చూడండి",
    searchRecords: "రికార్డులను శోధించండి",
    watchVideo: "వీడియో చూడండి",
    interactiveMap: "ఇంటరాక్టివ్ మ్యాప్",
    landMeasurement: "భూ కొలత",
    recordVerification: "రికార్డు తనిఖీ",
    detailedReports: "వివరమైన నివేదికలు",
    riskAnalysis: "రిస్క్ విశ్లేషణ",
    roleBasedAccess: "యాక్సెస్ నియంత్రణ",
    howItWorks: "ఇది ఎలా పనిచేస్తుంది",
    howItWorksSub: "భూ రికార్డులను తనిఖీ చేయడానికి సులభమైన ప్రక్రియ",
    searchLand: "భూమిని శోధించండి",
    exploreAnalyze: "విశ్లేషించండి",
    verifyRecords: "రికార్డులను తనిఖీ చేయండి",
    getReport: "నివేదిక పొందండి",
    transparentReady: "పారదర్శకమైన. నమ్మకమైన.",
    smarterApproach: "స్మార్ట్ భూ డేటా విధానం",
  },
  "ગુજરાતી (Gujarati)": {
    home: "મુખ્ય પૃષ્ઠ",
    land: "જમીન શોધ",
    notice: "સૂચનાઓ",
    measurements: "જમીન માપણી",
    verification: "ચકાસણી",
    resources: "સંસાધનો",
    help: "મદદ",
    login: "લોગીન",
    getStarted: "શરૂ કરો",
    heroTitlePre: "ડેટા અને નકશા દ્વારા સમજો ",
    heroTitleSpan: "જમીન રેકોર્ડ",
    heroSubtitle: "જમીન વિઝ્યુઅલાઇઝેશન અને રેકોર્ડ ચકાસણી માટે ઇન્ટરેક્ટિવ પ્લેટફોર્મ.",
    exploreMap: "નકશો જુઓ",
    searchRecords: "રેકોર્ડ શોધો",
    watchVideo: "વીડિયો જુઓ",
    interactiveMap: "ઇન્ટરેક્ટિવ નકશો",
    landMeasurement: "જમીન માપણી",
    recordVerification: "રેકોર્ડ ચકાસણી",
    detailedReports: "વિગતવાર અહેવાલો",
    riskAnalysis: "જોખમ વિશ્લેષણ",
    roleBasedAccess: "ઍક્સેસ નિયંત્રણ",
    howItWorks: "આ કેવી રીતે કામ કરે છે",
    howItWorksSub: "જમીનના રેકોર્ડ ચકાસવા માટે સરળ અને પારદર્શક પ્રક્રિયા",
    searchLand: "જમીન શોધો",
    exploreAnalyze: "શોધો અને વિશ્લેષણ કરો",
    verifyRecords: "રેકોર્ડ ચકાસો",
    getReport: "અહેવાલ મેળવો",
    transparentReady: "પારદર્શક. વિશ્વસનીય.",
    smarterApproach: "સ્માર્ટ જમીન ડેટા અભિગમ",
  },
  "বাংলা (Bengali)": {
    home: "হোম",
    land: "জমি সন্ধান",
    notice: "বিজ্ঞপ্তি",
    measurements: "জমি পরিমাপ",
    verification: "যাচাইকরণ",
    resources: "সম্পদ",
    help: "সাহায্য",
    login: "লগইন",
    getStarted: "শুরু করুন",
    heroTitlePre: "তথ্য ও মানচিত্রের মাধ্যমে বুঝুন ",
    heroTitleSpan: "জমির রেকর্ড",
    heroSubtitle: "প্লট ভিজ্যুয়ালাইজেশন এবং রেকর্ড যাচাইকরণের জন্য ইন্টারেক্টিভ প্ল্যাটফর্ম।",
    exploreMap: "মানচিত্র দেখুন",
    searchRecords: "রেকর্ড খুঁজুন",
    watchVideo: "ভিডিও দেখুন",
    interactiveMap: "ইন্টারেক্টিভ মানচিত্র",
    landMeasurement: "জমি পরিমাপ",
    recordVerification: "রেকর্ড যাচাইকরণ",
    detailedReports: "বিস্তারিত রিপোর্ট",
    riskAnalysis: "ঝুঁকি বিশ্লেষণ",
    roleBasedAccess: "ভূমিকাভিত্তিক অ্যাক্সেস",
    howItWorks: "এটি কীভাবে কাজ করে",
    howItWorksSub: "জমির রেকর্ড পরীক্ষা এবং যাচাই করার একটি সহজ ও স্বচ্ছ প্রক্রিয়া",
    searchLand: "জমি খুঁজুন",
    exploreAnalyze: "বিশ্লেষণ করুন",
    verifyRecords: "রেকর্ড যাচাই করুন",
    getReport: "রিপোর্ট পান",
    transparentReady: "স্বচ্ছ। নির্ভরযোগ্য।",
    smarterApproach: "স্মার্ট ল্যান্ড ডেটা পদ্ধতি",
  },
  "മലയാളം (Malayalam)": {
    home: "ഹോം",
    land: "ഭൂമി തിരച്ചിൽ",
    notice: "അറിയിപ്പുകൾ",
    measurements: "ഭൂ അളവ്",
    verification: "പരിശോധന",
    resources: "വിഭവങ്ങൾ",
    help: "സഹായം",
    login: "ലോഗിൻ",
    getStarted: "തുടങ്ങുക",
    heroTitlePre: "വിവരങ്ങളും ഭൂപടങ്ങളും വഴി മനസ്സിലാക്കുക ",
    heroTitleSpan: "ഭൂമി രേഖകൾ",
    heroSubtitle: "ഭൂമി പ്ലോട്ട് പരിശോധനയ്ക്കും രേഖകൾ സാധൂകരിക്കുന്നതിനുമുള്ള പ്ലാറ്റ്ഫോം.",
    exploreMap: "ഭൂപടം കാണുക",
    searchRecords: "രേഖകൾ തിരയുക",
    watchVideo: "വീഡിയോ കാണുക",
    interactiveMap: "ഇന്ററാക്ടീവ് മാപ്പ്",
    landMeasurement: "ഭൂ അളവ്",
    recordVerification: "രേഖ പരിശോധന",
    detailedReports: "വിശദമായ റിപ്പോർട്ടുകൾ",
    riskAnalysis: "സാധ്യതാ വിശകലനം",
    roleBasedAccess: "റോൾ അധിഷ്ഠിത ആക്സസ്",
    howItWorks: "ഇത് എങ്ങനെ പ്രവർത്തിക്കുന്നു",
    howItWorksSub: "ഭൂമി രേഖകൾ പരിശോധിക്കുന്നതിനുള്ള ലളിതമായ പ്രക്രിയ",
    searchLand: "ഭൂമി തിരയുക",
    exploreAnalyze: "വിശകലനം ചെയ്യുക",
    verifyRecords: "രേഖകൾ പരിശോധിക്കുക",
    getReport: "റിപ്പോർട്ട് നേടുക",
    transparentReady: "സുതാര്യമായ. വിശ്വസനീയമായ.",
    smarterApproach: "സ്മാർട്ട് ലാൻഡ് ഡാറ്റാ സമീപനം",
  },
  "ਪੰਜਾਬੀ (Punjabi)": {
    home: "ਮੁੱਖ ਪੰਨਾ",
    land: "ਜ਼ਮੀਨ ਦੀ ਖੋਜ",
    notice: "ਨੋਟਿਸ",
    measurements: "ਜ਼ਮੀਨ ਮਿਣਤੀ",
    verification: "ਤਸਦੀਕ",
    resources: "ਸਰੋਤ",
    help: "ਮਦਦ",
    login: "ਲੌਗਇਨ",
    getStarted: "ਸ਼ੁਰੂ ਕਰੋ",
    heroTitlePre: "ਡਾਟਾ ਅਤੇ ਨਕਸ਼ਿਆਂ ਰਾਹੀਂ ਸਮਝੋ ",
    heroTitleSpan: "ਜ਼ਮੀਨੀ ਰਿਕਾਰਡ",
    heroSubtitle: "ਜ਼ਮੀਨ ਦੇ ਰਿਕਾਰਡਾਂ ਦੀ ਜਾਂਚ ਅਤੇ ਤਸਦੀਕ ਲਈ ਇੱਕ ਇੰਟਰਐਕਟਿਵ ਪਲੇਟਫਾਰਮ।",
    exploreMap: "ਨਕਸ਼ਾ ਵੇਖੋ",
    searchRecords: "ਰਿਕਾਰਡ ਖੋਜੋ",
    watchVideo: "ਵੀਡੀਓ ਵੇਖੋ",
    interactiveMap: "ਇੰਟਰਐਕਟਿਵ ਨਕਸ਼ਾ",
    landMeasurement: "ਜ਼ਮੀਨ ਮਿਣਤੀ",
    recordVerification: "ਰਿਕਾਰਡ ਤਸਦੀਕ",
    detailedReports: "ਵਿਸਥਾਰਪੂਰਵਕ ਰਿਪੋਰਟਾਂ",
    riskAnalysis: "ਜੋਖਮ ਵਿਸ਼ਲੇਸ਼ਣ",
    roleBasedAccess: "ਰੋਲ ਅਧਾਰਤ ਪਹੁੰਚ",
    howItWorks: "ਇਹ ਕਿਵੇਂ ਕੰਮ ਕਰਦਾ ਹੈ",
    howItWorksSub: "ਜ਼ਮੀਨੀ ਰਿਕਾਰਡਾਂ ਦੀ ਜਾਂਚ ਲਈ ਇੱਕ ਸਰਲ ਅਤੇ ਪਾਰਦਰਸ਼ੀ ਪ੍ਰਕਿਰਿਆ",
    searchLand: "ਜ਼ਮੀਨ ਖੋਜੋ",
    exploreAnalyze: "ਵਿਸ਼ਲੇਸ਼ਣ ਕਰੋ",
    verifyRecords: "ਰਿਕਾਰਡ ਤਸਦੀਕ ਕਰੋ",
    getReport: "ਰਿਪੋਰਟ ਪ੍ਰਾਪਤ ਕਰੋ",
    transparentReady: "ਪਾਰਦਰਸ਼ੀ। ਭਰੋਸੇਯੋਗ।",
    smarterApproach: "ਸਮਾਰਟ ਜ਼ਮੀਨੀ ਡਾਟਾ ਪਹੁੰਚ",
  },
  "ଓଡ଼ିଆ (Odia)": {
    home: "ମୁଖ୍ୟ ପୃଷ୍ଠା",
    land: "ଜମି ସନ୍ଧାନ",
    notice: "ବିଜ୍ଞପ୍ତି",
    measurements: "ଜମି ମାପ",
    verification: "ଯାଞ୍ଚ",
    resources: "ସମ୍ବଳ",
    help: "ସହାୟତା",
    login: "ଲଗଇନ୍",
    getStarted: "ଆରମ୍ଭ କରନ୍ତୁ",
    heroTitlePre: "ତଥ୍ୟ ଏବଂ ମାନଚିତ୍ର ମାଧ୍ୟମରେ ବୁଝନ୍ତୁ ",
    heroTitleSpan: "ଜମି ରେକର୍ଡ",
    heroSubtitle: "ଜମି ରେକର୍ଡ ଯାଞ୍ଚ ଏବଂ ମାନଚିତ୍ର ଅନୁଧ୍ୟାନ ପାଇଁ ଏକ ସହଜ ପ୍ଲାଟଫର୍ମ।",
    exploreMap: "ମାନଚିତ୍ର ଦେଖନ୍ତୁ",
    searchRecords: "ରେକର୍ଡ ଖୋଜନ୍ତୁ",
    watchVideo: "ଭିଡିଓ ଦେଖନ୍ତୁ",
    interactiveMap: "ଇଣ୍ଟରାକ୍ଟିଭ୍ ମାନଚିତ୍ର",
    landMeasurement: "ଜମି ମାପ",
    recordVerification: "ରେକର୍ଡ ଯାଞ୍ଚ",
    detailedReports: "ବିସ୍ତୃତ ରିପୋର୍ଟ",
    riskAnalysis: "ବିପଦ ବିଶ୍ଳେଷଣ",
    roleBasedAccess: "ଅଧିକାର ଭିତ୍ତିକ ପ୍ରବେଶ",
    howItWorks: "ଏହା କିପରି କାମ କରେ",
    howItWorksSub: "ଜମି ରେକର୍ଡ ଯାଞ୍ଚ ପାଇଁ ଏକ ସରଳ ଏବଂ ସ୍ୱଚ୍ଛ ପ୍ରକ୍ରିୟା",
    searchLand: "ଜମି ଖୋଜନ୍ତୁ",
    exploreAnalyze: "ବିଶ୍ଳେଷଣ କରନ୍ତୁ",
    verifyRecords: "ରେକର୍ଡ ଯାଞ୍ଚ କରନ୍ତୁ",
    getReport: "ରିପୋର୍ଟ ପାଆନ୍ତୁ",
    transparentReady: "ସ୍ୱଚ୍ଛ। ବିଶ୍ୱସନୀୟ।",
    smarterApproach: "ସ୍ମାର୍ଟ ଜମି ତଥ୍ୟ ପଦ୍ଧତି",
  },
};

const LanguageContext = createContext<LanguageContextType>({
  language: "English",
  setLanguage: () => {},
  t: (key) => key,
});

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<SupportedLanguage>("English");

  useEffect(() => {
    const saved = localStorage.getItem("bhoomiverify_language") as SupportedLanguage;
    if (saved && translations[saved]) {
      setLanguage(saved);
    }
  }, []);

  const handleSetLanguage = (lang: SupportedLanguage) => {
    setLanguage(lang);
    localStorage.setItem("bhoomiverify_language", lang);
  };

  const t = (key: string): string => {
    return translations[language]?.[key] || translations["English"]?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
